### Products index
GET http://localhost:3000/products.json

### Products show
GET http://localhost:3000/products/3.json

### Products create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": " puffy coats",
  "price": 30.00,
  "description": "keeps you warm in the winter"
}

### Products update
PATCH http://localhost:3000/products/5.json
Content-Type: application/json

{
  "name": "glitter hats"
}

### Products destroy
DELETE http://localhost:3000/products/7.json