### Users create (signup)
POST http://localhost:3000/users.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjI3NzI0NDN9.7_jDKx3D6iNPNxRv26gTQ3GP3pN5txiV3iFxNffQfeE
Content-Type: application/json

{
  "name": "Big Test",
  "email": "Biggie@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Products index
GET http://localhost:3000/products.json

### Products show
GET http://localhost:3000/products/3.json

### Products create
POST http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjI3NzI0NDN9.7_jDKx3D6iNPNxRv26gTQ3GP3pN5txiV3iFxNffQfeE
Content-Type: application/json

{
  "name": " puffy coats",
  "price": 30.00,
  "description": "keeps you warm in the winter"
}

### Products update
PATCH http://localhost:3000/products/5.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjI3NzI0NDN9.7_jDKx3D6iNPNxRv26gTQ3GP3pN5txiV3iFxNffQfeE
Content-Type: application/json

{
  "name": "glitter hats"
}

### Products destroy
DELETE http://localhost:3000/products/7.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjI3NzI0NDN9.7_jDKx3D6iNPNxRv26gTQ3GP3pN5txiV3iFxNffQfeE

### Orders Create
POST http://localhost:3000/orders.json
Content-Type: application/json

{
"user_id": "1",
"product_id": 640,
"quantity": 480,
"subtotal": 4,
"tax": 2,
"total": 6
}